// app/routes/drawing.tsx
import { Container } from '../components/Container'
import type { Route } from './+types/drawing'

export const meta: Route.MetaFunction = () => {
  return [{ title: 'udrawing | Jason Kuhrt' }]
}

export default function udrawing() {
  return (
    <Container variant='content' className='prose dark:prose-invert mx-auto'>
      <h1>udrawing</h1>
      <p>Coming soon...</p>
    </Container>
  )
}

// src/routes/drawing/+page.svelte
<script lang="ts">
  import Section from '$lib/components/Section.svelte'
</script>

<svelte:head>
  <title>Drawing – Kuhrt</title>
  <meta name="description" content="Drawing work by Jason Kuhrt" />
</svelte:head>

<Section spacing="xl">
  <div class="container">
    <div class="max-w-3xl mx-auto">
      <p>Not ready yet. I will be curating a catalog of my open source work here.</p>
    </div>
  </div>
</Section>
