// src/routes/coding/+page.svelte
<script lang="ts">
  import Section from '$lib/components/Section.svelte'
  import Container from '$lib/components/Container.svelte'
  import Grid from '$lib/components/Grid.svelte'
  import RepoCard from '$lib/components/RepoCard.svelte'
  import GitHubProfileCard from '$lib/components/GitHubProfileCard.svelte'
  import RepoRefreshTimer from '$lib/components/RepoRefreshTimer.svelte'
  import { getRepoData, getRepoDataFetchedAt } from '$lib/github'

  const repos = getRepoData()
  const fetchedAt = getRepoDataFetchedAt()
</script>

<svelte:head>
  <title>Code – Kuhrt</title>
  <meta name="description" content="Open source projects by Jason Kuhrt" />
</svelte:head>

<Section spacing="xl">
  <Container variant="standard">
    <Grid cols={{ sm: 1, md: 2, lg: 3 }} gap="lg">
      <GitHubProfileCard />
      {#each repos as repo (repo.name)}
        <RepoCard {repo} />
      {/each}
    </Grid>
    <div class="mt-6 flex justify-end">
      <RepoRefreshTimer {fetchedAt} />
    </div>
  </Container>
</Section>

// app/routes/coding.tsx
import { Container } from '../components/Container'
import { Section } from '../components/Section'
import { Grid } from '../components/Grid'
import { GitHubProfileCard } from '../components/GitHubProfileCard'
import { RepoCard } from '../components/RepoCard'
import { RepoRefreshTimer } from '../components/RepoRefreshTimer'
import { getRepoData, getRepoDataFetchedAt } from '../lib/github'
import type { Route } from './+types/coding'

export const meta: Route.MetaFunction = () => {
  return [
    { title: 'Code – Jason Kuhrt' },
    {
      name: 'description',
      content: 'Open source projects by Jason Kuhrt',
    },
  ]
}

export default function Coding() {
  const repos = getRepoData()
  const fetchedAt = getRepoDataFetchedAt()

  return (
    <Section spacing="xl">
      <Container variant="standard">
        <Grid cols={{ sm: 1, md: 2, lg: 3 }} gap="lg">
          <GitHubProfileCard />
          {repos.map((repo) => <RepoCard key={repo.name} repo={repo} />)}
        </Grid>
        <div className="mt-6 flex justify-end">
          <RepoRefreshTimer fetchedAt={fetchedAt} />
        </div>
      </Container>
    </Section>
  )
}
