// app/components/Stack.tsx
/**
 * Stack component - vertical layout with consistent spacing
 *
 * Uses CSS gap for spacing between children
 */
export function Stack({
  spacing = 'base',
  className,
  children,
}: {
  spacing?: 'sm' | 'base' | 'lg' | 'xl'
  className?: string
  children?: React.ReactNode
}) {
  const spacingMap = {
    sm: 'var(--spacing-2)',
    base: 'var(--spacing-4)',
    lg: 'var(--spacing-6)',
    xl: 'var(--spacing-8)',
  }

  return (
    <div
      className={`stack ${className || ''}`}
      style={{
        '--stack-gap': spacingMap[spacing],
        display: 'flex',
        flexDirection: 'column',
        gap: 'var(--stack-gap)',
      } as React.CSSProperties}
    >
      {children}
    </div>
  )
}

// src/lib/components/Stack.svelte
<script lang="ts">
  /**
   * Stack component - vertical layout with consistent spacing
   *
   * Uses CSS gap for spacing between children
   */
  let {
    spacing = 'base',
    class: className,
    children,
  }: {
    spacing?: 'sm' | 'base' | 'lg' | 'xl'
    class?: string
    children?: any
  } = $props()

  const spacingMap = {
    sm: 'var(--spacing-2)',
    base: 'var(--spacing-4)',
    lg: 'var(--spacing-6)',
    xl: 'var(--spacing-8)',
  }
</script>

<div class="stack {className || ''}" style="--stack-gap: {spacingMap[spacing]}">
  {@render children?.()}
</div>

<style>
  .stack {
    display: flex;
    flex-direction: column;
    gap: var(--stack-gap);
  }
</style>
